# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: hassmic.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import Optional

import betterproto


class MediaPlayerState(betterproto.Enum):
    """
    https://developer.android.com/reference/androidx/media3/common/Player.State
    """

    STATE_UNKNOWN = 0
    STATE_IDLE = 1
    STATE_BUFFERING = 2
    STATE_PLAYING = 3
    STATE_PAUSED = 4


class MediaPlayerCommandId(betterproto.Enum):
    COMMAND_UNKNOWN = 0
    COMMAND_PLAY = 1
    COMMAND_PAUSE = 2
    COMMAND_STOP = 3


class MediaPlayerId(betterproto.Enum):
    """The different media players available"""

    ID_UNKNOWN = 0
    ID_PLAYBACK = 1
    """The normal music/audio playback player"""

    ID_ANNOUNCE = 2
    """The announce player"""


class LogSeverity(betterproto.Enum):
    SEVERITY_UNKNOWN = 0
    SEVERITY_DEBUG = 1
    SEVERITY_INFO = 2
    SEVERITY_WARNING = 3
    SEVERITY_ERROR = 4


@dataclass(eq=False, repr=False)
class SavedSettings(betterproto.Message):
    """Information saved and loaded between runs of the hassmic app"""

    announce_volume: Optional[float] = betterproto.float_field(1, optional=True)
    """The last volume of the `announce` player"""

    playback_volume: Optional[float] = betterproto.float_field(2, optional=True)
    """The last volume of the `playback` player"""

    hassmic_uuid: str = betterproto.string_field(3)
    """Hassmic UUID"""

    device_name: str = betterproto.string_field(4)
    """Device name"""


@dataclass(eq=False, repr=False)
class ClientInfo(betterproto.Message):
    """Information that the client sends about itself"""

    version: str = betterproto.string_field(1)
    """The version, for example "0.9.2"""

    uuid: str = betterproto.string_field(2)
    """The uuid of this client"""


@dataclass(eq=False, repr=False)
class Ping(betterproto.Message):
    """A ping message"""

    pass


@dataclass(eq=False, repr=False)
class AudioData(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class MediaPlayerCommand(betterproto.Message):
    """A command paired with a player"""

    id: "MediaPlayerId" = betterproto.enum_field(1)
    command: "MediaPlayerCommandId" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class MediaPlayerVolume(betterproto.Message):
    """A media player has changed volume"""

    player: "MediaPlayerId" = betterproto.enum_field(1)
    volume: float = betterproto.float_field(2)


@dataclass(eq=False, repr=False)
class DeviceVolume(betterproto.Message):
    """The device volume has changed"""

    volume: float = betterproto.float_field(1)


@dataclass(eq=False, repr=False)
class MediaPlayerStateChange(betterproto.Message):
    """A media player has changed state"""

    player: "MediaPlayerId" = betterproto.enum_field(1)
    new_state: "MediaPlayerState" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class ClientEvent(betterproto.Message):
    """Tell the server that a client event occurred"""

    media_player_state_change: "MediaPlayerStateChange" = betterproto.message_field(
        1, group="event"
    )
    media_player_volume_change: "MediaPlayerVolume" = betterproto.message_field(
        2, group="event"
    )
    device_volume_change: "DeviceVolume" = betterproto.message_field(3, group="event")
    log: "Log" = betterproto.message_field(4, group="event")


@dataclass(eq=False, repr=False)
class Log(betterproto.Message):
    """A log message passed from the client to the server"""

    log_text: str = betterproto.string_field(1)
    severity: "LogSeverity" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class ClientMessage(betterproto.Message):
    """The wrapper message that actually gets sent to the server"""

    ping: "Ping" = betterproto.message_field(1, group="msg")
    client_info: "ClientInfo" = betterproto.message_field(2, group="msg")
    audio_data: "AudioData" = betterproto.message_field(3, group="msg")
    client_event: "ClientEvent" = betterproto.message_field(4, group="msg")
    saved_settings: "SavedSettings" = betterproto.message_field(5, group="msg")


@dataclass(eq=False, repr=False)
class PlayAudio(betterproto.Message):
    """Play an audio file"""

    announce: bool = betterproto.bool_field(1)
    """Whether this should be an announcement or not"""

    url: str = betterproto.string_field(2)
    """The url to play"""


@dataclass(eq=False, repr=False)
class HassmicCommand(betterproto.Message):
    """
    The wrapper message that gets sent either from the server to the client or
     used internally between layers in the client
    """

    play_audio: "PlayAudio" = betterproto.message_field(1, group="msg")
    """A command to play audio"""

    set_mic_mute: bool = betterproto.bool_field(2, group="msg")
    """Set whether the mic should be muted"""

    set_device_volume: "DeviceVolume" = betterproto.message_field(3, group="msg")
    """Set the volume of the device"""

    set_player_volume: "MediaPlayerVolume" = betterproto.message_field(4, group="msg")
    """Set the volume of a player"""

    command: "MediaPlayerCommand" = betterproto.message_field(5, group="msg")
    """Play, pause, stop, etc"""

    internal: bool = betterproto.bool_field(6)
