// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hassmic.proto
// Protobuf Java Version: 4.29.2

package com.thejeffcooper.hassmic.proto;

public interface DeviceVolumeOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.DeviceVolume)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>float volume = 1;</code>
   *
   * @return The volume.
   */
  float getVolume();
}
