// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hassmic.proto
// Protobuf Java Version: 4.29.2

package com.thejeffcooper.hassmic.proto;

public final class Hassmic {
  private Hassmic() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
