// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * An event from the wyoming server
 * </pre>
 *
 * Protobuf type {@code hassmic.WyomingEvent}
 */
public final class WyomingEvent
    extends com.google.protobuf.GeneratedMessageLite<WyomingEvent, WyomingEvent.Builder>
    implements
    // @@protoc_insertion_point(message_implements:hassmic.WyomingEvent)
    WyomingEventOrBuilder {
  private WyomingEvent() {
    rawJson_ = "";
  }

  public static final int RAW_JSON_FIELD_NUMBER = 1;
  private java.lang.String rawJson_;

  /**
   * <code>string raw_json = 1;</code>
   *
   * @return The rawJson.
   */
  @java.lang.Override
  public java.lang.String getRawJson() {
    return rawJson_;
  }

  /**
   * <code>string raw_json = 1;</code>
   *
   * @return The bytes for rawJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRawJsonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(rawJson_);
  }

  /**
   * <code>string raw_json = 1;</code>
   *
   * @param value The rawJson to set.
   */
  private void setRawJson(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    rawJson_ = value;
  }

  /** <code>string raw_json = 1;</code> */
  private void clearRawJson() {

    rawJson_ = getDefaultInstance().getRawJson();
  }

  /**
   * <code>string raw_json = 1;</code>
   *
   * @param value The bytes for rawJson to set.
   */
  private void setRawJsonBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    rawJson_ = value.toStringUtf8();
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.thejeffcooper.hassmic.proto.WyomingEvent prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * An event from the wyoming server
   * </pre>
   *
   * Protobuf type {@code hassmic.WyomingEvent}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.thejeffcooper.hassmic.proto.WyomingEvent, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:hassmic.WyomingEvent)
      com.thejeffcooper.hassmic.proto.WyomingEventOrBuilder {
    // Construct using com.thejeffcooper.hassmic.proto.WyomingEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     * <code>string raw_json = 1;</code>
     *
     * @return The rawJson.
     */
    @java.lang.Override
    public java.lang.String getRawJson() {
      return instance.getRawJson();
    }

    /**
     * <code>string raw_json = 1;</code>
     *
     * @return The bytes for rawJson.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawJsonBytes() {
      return instance.getRawJsonBytes();
    }

    /**
     * <code>string raw_json = 1;</code>
     *
     * @param value The rawJson to set.
     * @return This builder for chaining.
     */
    public Builder setRawJson(java.lang.String value) {
      copyOnWrite();
      instance.setRawJson(value);
      return this;
    }

    /**
     * <code>string raw_json = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRawJson() {
      copyOnWrite();
      instance.clearRawJson();
      return this;
    }

    /**
     * <code>string raw_json = 1;</code>
     *
     * @param value The bytes for rawJson to set.
     * @return This builder for chaining.
     */
    public Builder setRawJsonBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRawJsonBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:hassmic.WyomingEvent)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.thejeffcooper.hassmic.proto.WyomingEvent();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "rawJson_",
              };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.thejeffcooper.hassmic.proto.WyomingEvent> parser = PARSER;
          if (parser == null) {
            synchronized (com.thejeffcooper.hassmic.proto.WyomingEvent.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.thejeffcooper.hassmic.proto.WyomingEvent>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:hassmic.WyomingEvent)
  private static final com.thejeffcooper.hassmic.proto.WyomingEvent DEFAULT_INSTANCE;

  static {
    WyomingEvent defaultInstance = new WyomingEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WyomingEvent.class, defaultInstance);
  }

  public static com.thejeffcooper.hassmic.proto.WyomingEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<WyomingEvent> PARSER;

  public static com.google.protobuf.Parser<WyomingEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
