// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface WyomingEventOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.WyomingEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string raw_json = 1;</code>
   *
   * @return The rawJson.
   */
  java.lang.String getRawJson();

  /**
   * <code>string raw_json = 1;</code>
   *
   * @return The bytes for rawJson.
   */
  com.google.protobuf.ByteString getRawJsonBytes();
}
