name: react-native-android-build-dev-apk
on:
  push:
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          apt-get update && apt-get install -y npm
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: app-latest.apk
          path: android/app/build/outputs/apk/release/
      - name: Upload to B2 by SHA
        uses: jeffc/backblaze-b2-upload-action@testing
        with:
          key_id: ${{ secrets.B2_APPKEY_ID }}
          application_key: ${{ secrets.B2_APPKEY_SECRET }}
          bucket_name: ${{ secrets.B2_BUCKET }}
          remote_path: hassmic-artifacts/by-hash/hassmic-${{ github.sha }}.apk
          file_path: android/app/build/outputs/apk/release/app-release.apk
      - name: Upload to B2 by Branch
        uses: jeffc/backblaze-b2-upload-action@testing
        with:
          key_id: ${{ secrets.B2_APPKEY_ID }}
          application_key: ${{ secrets.B2_APPKEY_SECRET }}
          bucket_name: ${{ secrets.B2_BUCKET }}
          remote_path: hassmic-artifacts/by-branch/hassmic-${{ github.ref_name }}.apk
          file_path: android/app/build/outputs/apk/release/app-release.apk
